name: Discord Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl

      - name: Send failure notification to Discord
        shell: bash 
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"CI Job Passed\",
                   \"description\": \"A CI job has passed.\",
                   \"color\": 16711680,
                   \"fields\": [
                     {
                       \"name\": \"Commit:\",
                       \"value\": \"[\`$COMMIT_HASH\`](<${{ github.event.head_commit.url }}>) ${{ github.event.head_commit.message }}\",
                       \"inline\": false
                     },
                     {
                       \"name\": \"Committed by:\",
                       \"value\": \"[${{ github.actor }}](https://github.com/${{ github.actor }})\",
                       \"inline\": false
                     }
                   ]
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK_3 }}

      - name: Send Discord Notification
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "New Commit Pushed!",
              "color": 65280,
              "fields": [
                {
                  "name": "Download",
                  "value": "[Click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ env.artifact_id }})",
                  "inline": false
                },
                {
                  "name": "Commit",
                  "value": "[`'"$COMMIT_HASH"'`](<https://github.com/${{ github.repository }}/commit/${{ github.sha }}>) - ${{ github.event.head_commit.message }}",
                  "inline": false
                }
              ]
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_3 }}
