name: Discord Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -d '{"content": "A new commit has been pushed to the repository!"}' \
               ${{ secrets.DISCORD_WEBHOOK_3 }}
