name: Discord Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl

      - name: Send Discord Notification
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"A new commit ($COMMIT_HASH) has been pushed to the repository!\"}" \
               ${{ secrets.DISCORD_WEBHOOK_3 }}
