name: Discord Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl zip

      - name: Zip the patch
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:7}"
          ZIP_NAME="Pokemon_YAEEH_${COMMIT_HASH}.zip"
          zip -j "$ZIP_NAME" assets/Pokemon_YAEEH.bps
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Upload to Catbox
        id: upload
        run: |
          RESPONSE=$(curl -s -F "reqtype=fileupload" -F "fileToUpload=@${{ env.ZIP_NAME }}" https://catbox.moe/user/api.php)
          echo "DOWNLOAD_URL=$RESPONSE" >> $GITHUB_ENV

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"New Patch Uploaded!\",
                   \"color\": 65280,
                   \"fields\": [
                     {
                       \"name\": \"Download:\",
                       \"value\": \"[Click here](${{ env.DOWNLOAD_URL }})\",
                       \"inline\": false
                     },
                     {
                       \"name\": \"Commit:\",
                       \"value\": \"[\`${{ env.COMMIT_HASH }}\`](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) - ${{ github.event.head_commit.message }}\",
                       \"inline\": false
                     },
                     {
                       \"name\": \"Author:\",
                       \"value\": \"[${{ github.actor }}](https://github.com/${{ github.actor }})\",
                       \"inline\": false
                     }
                   ]
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK_3 }}
