name: Discord Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl

      - name: Send failure notification to Discord
        shell: bash 
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                 \"embeds\": [{
                   \"title\": \"CI Job Passed\",
                   \"description\": \"A CI job has passed.\",
                   \"color\": 16711680,
                   \"fields\": [
                     {
                       \"name\": \"Commit:\",
                       \"value\": \"[\`$COMMIT_HASH\`](<${{ github.event.head_commit.url }}>) ${{ github.event.head_commit.message }}\",
                       \"inline\": false
                     },
                     {
                       \"name\": \"Committed by:\",
                       \"value\": \"[${{ github.actor }}](https://github.com/${{ github.actor }})\",
                       \"inline\": false
                     }
                   ]
                 }]
               }" \
               ${{ secrets.DISCORD_WEBHOOK_3 }}

      - name: Send Discord Notification
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"
          COMMIT_URL="$REPO_URL/commit/${GITHUB_SHA}"
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"A new commit [\`$COMMIT_HASH\`](<$COMMIT_URL>) has been pushed to the repository!\"}" \
               ${{ secrets.DISCORD_WEBHOOK_3 }}
