name: Discord Notification on Push

on: push

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set up commit info and send to Discord
        shell: bash
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "New Commit Pushed!",
              "color": 65280,
              "fields": [
                {
                  "name": "Download",
                  "value": "[Click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ env.artifact_id }})",
                  "inline": false
                },
                {
                  "name": "Commit",
                  "value": "[`'"$COMMIT_HASH"'`](<https://github.com/${{ github.repository }}/commit/${{ github.sha }}>) - ${{ github.event.head_commit.message }}",
                  "inline": false
                }
              ]
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_3 }}
