name: Discord Notification on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl zip jq

      - name: Rename and zip the patch
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:7}"
          PATCH_NAME="pokeyaeeh_${COMMIT_HASH}.bps"
          cp assets/Pokemon_YAEEH.bps "$PATCH_NAME"
          zip -j patch.zip "$PATCH_NAME"
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV
          echo "PATCH_NAME=$PATCH_NAME" >> $GITHUB_ENV

      - name: Upload to Pixeldrain
        id: upload
        run: |
          echo "Uploading patch.zip to Pixeldrain..."
          RESPONSE=$(curl -s -F "file=@patch.zip" https://pixeldrain.com/api/file)
          echo "Pixeldrain raw response:"
          echo "$RESPONSE"
          echo "$RESPONSE" | jq .
          DOWNLOAD_ID=$(echo "$RESPONSE" | jq -r '.id')
          DOWNLOAD_URL="https://pixeldrain.com/api/file/${DOWNLOAD_ID}?download"
          echo "DOWNLOAD_URL=$DOWNLOAD_URL" >> $GITHUB_ENV

      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -n \
                 --arg url "$DOWNLOAD_URL" \
                 --arg commit "$COMMIT_HASH" '{
                   embeds: [ {
                     title: "Patch created!",
                     color: 65280,
                     fields: [
                       {
                         name: "Download:",
                         value: ("[__**Click here**__](" + $url + ")"),
                         inline: false
                       },
                       {
                         name: "Commit hash:",
                         value: ("`" + $commit + "`"),
                         inline: false
                       }
                     ]
                   }]
                 }')" \
               ${{ secrets.DISCORD_WEBHOOK_3 }}
