name: Discord Notification on Push

on: 
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Set Commit Hash and Author Details
        run: |
          COMMIT_HASH="${GITHUB_SHA:0:6}"
          AUTHOR_NAME="${{ github.actor }}"
          AUTHOR_URL="https://github.com/${{ github.actor }}"
          AUTHOR_ICON="https://github.com/${{ github.actor }}.png"

      - name: Send Discord Notification
        env:
          COMMIT_HASH: "${GITHUB_SHA:0:6}"
          AUTHOR_NAME: "${{ github.actor }}"
          AUTHOR_URL: "https://github.com/${{ github.actor }}"
          AUTHOR_ICON: "https://github.com/${{ github.actor }}.png"
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "Patch Created!",
              "url": "${{ github.event.head_commit.url }}",
              "color": 65280,
              "author": {
                "name": "'"${AUTHOR_NAME}"'",
                "url": "'"${AUTHOR_URL}"'",
                "icon_url": "'"${AUTHOR_ICON}"'"
              },
              "fields": [
                {
                  "name": "Download",
                  "value": "[Click here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ env.artifact_id }})",
                  "inline": false
                },
                {
                  "name": "Commit",
                  "value": "[\`'"$COMMIT_HASH"'\`](<${{ github.event.head_commit.url }>) - ${{ github.event.head_commit.message }}",
                  "inline": false
                }
              ]
            }]
          }' \
          ${{ secrets.DISCORD_WEBHOOK_3 }}
